### ISSUE TITLE
SetAuthCookie(ticket) doesn't create any ticket

### ISSUE THREAD

**Issue by stefanoberetta** [apereo/dotnet-cas-client#105]
Hi!
After a successfully login I try to set the CAS cookie using `DotNetCasClient.CasAuthentication.SetAuthCookie(t);`
But it seems it doesn't create any cookie.
Could it be the framework 4.7.2?

Thank you
S

**Comment by phantomtypist** [comment]
ASP.NET WebForms, Web Pages or MVC?  Which version of those are you using also?  Can you also provide a snippet of your web.config, without anything sensitive, for the <casClientConfig> and <forms> sections.  Are you using the latest NuGet package in your project?

Do you get an errors?

**Comment by phantomtypist** [comment]
Also, which ticket storage implementation are you using?   The default is in-memory, but there are a few other providers we offer.

**Comment by phantomtypist** [comment]
Did your code work in the same project targeting a prior version of the .NET framework? e.g. 4.5?  I.e. was this code ever working at one point and magically one day it stopped?

**Comment by TheHokieCoder** [comment]
Closing due to lack of response from the OP.
