### ISSUE TITLE
CAS redirects to servername instead of service

### ISSUE THREAD

**Issue by lukassr** [apereo/dotnet-cas-client#106]
Hi. I have an application that have a valid CAS auth, but it always redirects to the `serverName`. I want it to be able to redirect to the previous page (`service` attribute) which the user came to make the CAS auth. Is it possible?

Thanks you very much.

**Comment by phantomtypist** [comment]
Can you please provide an example of how your **forms** and **casClientConfig** sections are configured?  I. E. Just replace your domain with **example.org** and leave the rest.

**Comment by TheHokieCoder** [comment]
Closing due to lack of response from the OP.
