### ISSUE TITLE
/signin-cas?state=xxx

### ISSUE THREAD

**Issue by zhaoyanwenqi** [apereo/dotnet-cas-client#113]
.net core 3.1
 Jump after authentication / sign CAS? State = XXX what's wrong with this address?

**Comment by phantomtypist** [comment]
You're going to have to give us more information.  I have no clue what you just typed in.

**Comment by zhaoyanwenqi** [comment]
.cn/signin-cas?state=CfDJ8FlcKjJTmoxCjlUlBq-h_aO8hVRppinBN07tRW&nbsp;&nbsp;

return
Status Code: 404; Not Found      Do you have a. Net core SDK?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apereo/dotnet-cas-client"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月16日(星期五) 下午3:11
收件人:&nbsp;"apereo/dotnet-cas-client"<dotnet-cas-client@noreply.github.com&gt;;
抄送:&nbsp;"Always"<305353941@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apereo/dotnet-cas-client] /signin-cas?state=xxx (#113)





 
You're going to have to give us more information.  I have no clue what you just typed in.

**Comment by phantomtypist** [comment]
This specific project does not work with .NET Core projects.
