### ISSUE TITLE
Is it support  SAML 2.0 ?

### ISSUE THREAD

**Issue by Gavinluo** [apereo/dotnet-cas-client#116]
readme list support saml 1.1 ， https://apereo.github.io/cas list support saml 2.0  ？ may i use this client for saml 2.0 ?

**Comment by Clamsik** [comment]
What version are you talking about? I Need to know of 3.1.10 version support It.

**Comment by phantomtypist** [comment]
> What version are you talking about? I Need to know of 3.1.10 version support It.

If you look at the code in the repo you'll see there is no SAML 3.1.10 support.

**Comment by phantomtypist** [comment]
> readme list support saml 1.1 ， https://apereo.github.io/cas list support saml 2.0 ？ may i use this client for saml 2.0 ?

Did you try it?

<blockquote><div><strong><a href="https://apereo.github.io/cas">CAS Server Documentation Home</a></strong></div></blockquote>

**Comment by Gavinluo** [comment]
I implemented this myself
