### ISSUE TITLE
Support for .net 5?

### ISSUE THREAD

**Issue by elbulla** [apereo/dotnet-cas-client#125]
I used the client to integrate successfully with .net framework applications, but I also have a .net 5 application where the client does not appear to work. In fact I do get warning that my project target of 'net5.0' may not by compatible. Are there any updates or tricks to work with .net 5+ versions? Maybe another client project I'm not aware of? Thank you!

**Comment by phantomtypist** [comment]
I'd suggest the packages from this "suite" of packages for .NET v5+:

- https://www.nuget.org/packages/GSS.Authentication.CAS.Core
- https://www.nuget.org/packages/GSS.Authentication.CAS.AspNetCore
- https://www.nuget.org/packages/GSS.Authentication.CAS.Owin

<blockquote><img src="https://nuget.org/Content/gallery/img/default-package-icon-256x256.png" width="48" align="right"><div><strong><a href="https://nuget.org/packages/GSS.Authentication.CAS.Core/">GSS.Authentication.CAS.Core 5.5.0</a></strong></div><div>Core components for CAS Authentication</div></blockquote>
<blockquote><img src="https://nuget.org/Content/gallery/img/default-package-icon-256x256.png" width="48" align="right"><div><strong><a href="https://nuget.org/packages/GSS.Authentication.CAS.AspNetCore/">GSS.Authentication.CAS.AspNetCore 5.5.0</a></strong></div><div>ASP.NET Core Middlewares for CAS Authentication</div></blockquote>
<blockquote><img src="https://nuget.org/Content/gallery/img/default-package-icon-256x256.png" width="48" align="right"><div><strong><a href="https://nuget.org/packages/GSS.Authentication.CAS.Owin/">GSS.Authentication.CAS.Owin 5.5.0</a></strong></div><div>OWIN Middlewares for CAS Authentication</div></blockquote>
