### ISSUE TITLE
ProcessRequestAuthentication using stale Ticket

### ISSUE THREAD

**Issue by Jetski5822** [apereo/dotnet-cas-client#13]
https://github.com/Jasig/dotnet-cas-client/blob/master/DotNetCasClient/CasAuthenticationModule.cs

method OnAuthenticateRequest 

line 144 CasAuthentication.ProcessTicketValidation();
This method checked for a new ticket, it then places this in to the Response, The next call is 

line 148 CasAuthentication.ProcessRequestAuthentication() 
This method uses the ticket from the previous request, and not the new one.

Do you know why? This means that the CAS Principle is not updated on the request leaving it stale.

**Comment by phantomtypist** [comment]
Fixed in pull request #71.

**Comment by phantomtypist** [comment]
Included in release 1.2.0
