### ISSUE TITLE
Not being redirected

### ISSUE THREAD

**Issue by johnrickman** [apereo/dotnet-cas-client#16]
Thanks for this library! 

However, my site isn't being redirected to the provided URL. I'm not seeing any valuable logging in order to diagnose, only the web.config attributes. Is there a rewrite value or something that I should be checking for that would prevent the redirection?

**Comment by hokiecoder** [comment]
@johnrickman are you still experiencing this issue? I assume probably not since it's been 2.5 years. I am trying to help clean up the open issues with this project, so if you still need help I will do my best to assist! If not, we should get this issue closed.

**Comment by johnrickman** [comment]
I think it was resolved.
