### ISSUE TITLE
Missing legacy files

### ISSUE THREAD

**Issue by ghost** [apereo/dotnet-cas-client#29]
This seems pretty trivial, but annoying right off from the clone.  

DotNetCasClient.csproj has references to the following legacy files:  

```
dotnet-cas-client/DotNetCasClient/LICENSE.txt
dotnet-cas-client/DotNetCasClient/NOTICE.txt
dotnet-cas-client/DotNetCasClient/lib/log4net.dll
```

**Comment by mmoayyed** [comment]
Could I ask you to submit a PR to get this fixed?

**Comment by vaeringjar** [comment]
Sure no problem. I'm in the middle of tracking down something else internal. I should get to it sometime today or tomorrow.

**Comment by hokiecoder** [comment]
@serac can close this issue now that the PR has been merged?
