### ISSUE TITLE
Move to Apereo org on Github

### ISSUE THREAD

**Issue by mmoayyed** [apereo/dotnet-cas-client#44]
Planning to move the repo to the Apereo org here on Github by Friday. Please speak up if you see an issue with that plan.

**Comment by serac** [comment]
Believe we can close, no?

**Comment by mmoayyed** [comment]
Possibly. We might want to rename this issue to also account for package names.

**Comment by phantomtypist** [comment]
@mmoayyed can you please elaborate, if you remember :), on your last comment so I can understand the intention better?

**Comment by mmoayyed** [comment]
Sorry for the delay. Chaotic day. 

So I may have been totally off-base since I now realize namespaces have no references to "jasig". So this can be closed, but you may want to take a pass update all refs from Jasig to Apereo. This may include license headers, readmes, etc.

**Comment by phantomtypist** [comment]
Gotcha.

**Comment by phantomtypist** [comment]
And I totally understand... this is open-source... not our day jobs.

**Comment by phantomtypist** [comment]
Done.

I left "jasig" in the namespaces of the Java client references that are in the comments throughout.  I looked over at the Java client code and they never changed the namespaces so I figured leave it alone here.
