### ISSUE TITLE
Push new Nuget Packages

### ISSUE THREAD

**Issue by LiamBateman** [apereo/dotnet-cas-client#47]
The Nuget package seems to be missing this issue, which has been a significant problem for us - https://github.com/apereo/dotnet-cas-client/commit/36ca258371b1a546189547a52f7ec9c3d53bc30b

Are there any plans for a 1.0.3 release?

**Comment by courchal** [comment]
Any development here?

**Comment by serac** [comment]
We take security bugs pretty seriously and I do try to review/accept pull requests that fix patent bugs, but that's about it. There's there's been no substantive development in well over a year. I've tried to recruit developers at my institution without much luck.

**Comment by phantomtypist** [comment]
@LiamBateman Can you please take a look at my last comment on issue #54?  There is a pre-release of the nuget package for version 1.1.0 and it includes the changeset you referenced.

**Comment by phantomtypist** [comment]
@LiamBateman @courchal 

Version 1.1.0 released to nuget.org.
