### ISSUE TITLE
The demo project still work?

### ISSUE THREAD

**Issue by drma-dev** [apereo/dotnet-cas-client#48]
I implemented the demo, clicked the login button redirects to the CAS login screen, returned to the demo project and still not displaying any information.

**Comment by phantomtypist** [comment]
"ExampleWebSite" or "ProxyDemoApp"?

**Comment by eastsea2** [comment]
I am trying to set up the ExampleWebSite. I gave me this error message
&&&&&&&&&&&&&&&&&&&&&&&&&&&&
The page isn’t redirecting properly
Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
    This problem can sometimes be caused by disabling or refusing to accept cookies.
&&&&&&&&&&&&&&&&&&&&&&&&&&&&
 Can you help me what is wrong on my web.config?
This is the lines I edited in the file:
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
<casClientConfig 
        casServerLoginUrl="https://login.vcu.edu/cas/login" 
        casServerUrlPrefix="https://login.vcu.edu/cas/" 
        serverName="donghai.vcu.edu/CAS1.1/ExampleWebSite/" 
       ............
        <authentication mode="Forms">
            <forms 
                loginUrl="https://login.vcu.edu/cas/login" 
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
Thanks.

**Comment by phantomtypist** [comment]
@dhiogoacioli if you feel like updating the example application to get it working, let me know here.  PR's welcome :)
