### ISSUE TITLE
Create and publish symbol package

### ISSUE THREAD

**Issue by phantomtypist** [apereo/dotnet-cas-client#62]
Create and publish symbol packages ~~on www.symbolsource.org (for production NuGet packages) and~~ on MyGet for ~~pre-release~~ all NuGet packages.

The symbol package will greatly enhance the debugging experience for anyone using the .NET CAS Client.

- MSDN Docs about symbol packages: https://msdn.microsoft.com/en-us/library/ms241613.aspx
- How to use symbol packages in VS: http://www.symbolsource.org/Public/Home/VisualStudio

**Comment by phantomtypist** [comment]
To simply things, I'm going to just publish the symbols to *only* MyGet's symbol server.  All the versions of the package are already stored on MyGet to begin with.  Production ones are pushed to NuGet.org.

Going forward users would need to add the MyGet symbol server feed(s) to their Visual Studio (Ref: https://docs.myget.org/docs/reference/symbols)

**Comment by TheHokieCoder** [comment]
Good work, Jason. Perhaps leave this issue open until instructions can be added to the readme/wiki on how to consume the symbols package(s) while debugging?

**Comment by phantomtypist** [comment]
Documented!

We should probably restructure the Wiki at a point in the near future as we add more stuff to it, like a troubleshooting section.

**Comment by phantomtypist** [comment]
Included in release 1.2.0
