### ISSUE TITLE
Store service ticket in sql database support?

### ISSUE THREAD

**Issue by satnamsarai** [apereo/dotnet-cas-client#69]

**Comment by satnamsarai** [comment]
Allow to save service tickets to database I.e sql

**Comment by phantomtypist** [comment]
This is pretty much what issue #61 is about.  I have updated the issue to reflect SQL Server.

**Comment by satnamsarai** [comment]
Great. Thanks

**Comment by TheHokieCoder** [comment]
@satnamsarai I was interested in this for one of my own projects, so I will keep you in mind as I help develop a solution that supports, in my case, a Microsoft SQL Server database. Comment on issue #61 with any requirements or feature requests that you might have and make sure to specify that it applies to a SQL DB backend.

**Comment by phantomtypist** [comment]
@satnamsarai to add to what @TheHokieCoder said, if I made the wrong assumption about SQL Server and you instead meant MySQL, Postgres, etc... please clarify that for us in a comment on issue #61.

Thanks!
