### ISSUE TITLE
Using Custom Login Page with Dotnet CAS Client

### ISSUE THREAD

**Issue by kritulrathod** [apereo/dotnet-cas-client#79]
Hi,

We had a query implementing the login page redirect using DotNetCasClient 1.1.0 client.

We want to have a custom UI for the login page where the CAS login shuld be displayed in an IFRAME. 

We created a page and updated the URL to `<forms loginUrl="https://www.myapp.com/login">`
however in the [documentation](https://wiki.jasig.org/display/casc/.net+cas+client) - it says that it is necessary to match the URL specified in `<casServerLoginUrl>` and `<forms>` element in the config.

Please advise how we can redirect the unauthenticated requests to - "https://www.myapp.com/login" instead of the "https://sso.myapp.com/cas/login" URL (which is SSO Blue Login Screen ).

Thanks in advance.
Regards, 
Kritul

**Comment by eastsea2** [comment]
Have you find the answer for this?
If so, can you share it with me?
Thanks.

**Comment by phantomtypist** [comment]
With your requirement it be inside an iframe I'm not really sure I can help here.  I really have no experience with the way you are trying/wanting to make it all work.

I'd say just customize your CAS login page to look like, or be that of, what you have on https://www.myapp.com/login.
