### ISSUE TITLE
SingleSignOut cause A potentially dangerous Request.Form value was detected from the client

### ISSUE THREAD

**Issue by nightBaker** [apereo/dotnet-cas-client#80]
After logout CAS sends post request message=<samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="LR-177-X8BLQyvy76SFszPwCMYwpFeF" Version="2.0" IssueInstant="2018-04-12T15:07:21Z"><saml:NameID xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">@NOT_USED@</saml:NameID><samlp:SessionIndex>ST-2171-iZF3BlhCp9VdarvPV-tJ1GEebO0-kaspi-portsso1</samlp:SessionIndex></samlp:LogoutRequest>,asynchronous=false,contentType=application/x-www-form-urlencoded

And dotnet-cas-client tryes get logoutRequest from HttpContext.Current.Request.Form

```
internal static void ProcessSingleSignOutRequest()
        {
            HttpContext context = HttpContext.Current;
            HttpRequest request = context.Request;
            HttpResponse response = context.Response;
            protoLogger.Debug("Examining request for single sign-out signature");

            if (request.HttpMethod == "POST" && request.Form["logoutRequest"] != null)
            {
```
getting value is causing exception - context.Request.Form["logoutRequest"]	'context.Request.Form["logoutRequest"]' threw an exception of type 'System.Web.HttpRequestValidationException'	string {System.Web.HttpRequestValidationException}

**Comment by phantomtypist** [comment]
Closing this because the discussion can be carried on in PR #83
